/**
 * verract contract configuration.
 *
 * Active workflow: VERIFY → RESOLVE → ACTION.
 */

var VERRACT_DEFAULT_BATCH_SIZE = 20;
var VERRACT_MAX_BATCH_SIZE = 200;
var VERRACT_TIME_BUDGET_MS = 270000;
var VERRACT_CONTINUATION_DELAY_MS = 60000;

var RESOLVE_SUGGESTION_MIN_SIMILARITY = 0.90;
var RESOLVE_SUGGESTION_MAX_ITEMS = 5;
var RESOLVE_SEARCH_MAX_TERMS = 5;
var RESOLVE_SEARCH_MAX_CANDIDATES = 200;

var VERRACT_PHASE_VERIFY = 'VERIFY';
var VERRACT_PHASE_RESOLVE = 'RESOLVE';
var VERRACT_PHASE_ACTION = 'ACTION';

var VERIFY_REPORT_FIELDS = [
  'Exists',
  'CheckedPathCount',
  'MatchedPathColumn',
  'Error'
];

var RESOLVE_REPORT_FIELDS = [
  'ResolveStatus',
  'ResolveID',
  'ResolveCandidateCount',
  'ResolveNote'
];

var SHARED_OUTPUT_FIELDS = [
  'SharedPathID',
  'SharedFileID',
  'SharedPath',
  'SharedFilename',
  'SharedSource'
];

var ACTION_OUTPUT_FIELDS = [
  'ActionStatus',
  'ActionID',
  'ActionAt',
  'ActionNote'
];

var RESOLVE_STATUSES = {
  SKIPPED_VERIFY_TRUE: 'SKIPPED_VERIFY_TRUE',
  RESOLVED: 'RESOLVED',
  PATH_FOUND_FILE_MISSING: 'PATH_FOUND_FILE_MISSING',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  AMBIGUOUS: 'AMBIGUOUS',
  INVALID_INPUT: 'INVALID_INPUT'
};

var VERIFY_ERRORS = {
  INVALID_INPUT: 'INVALID_INPUT',
  PATH_NOT_FOUND: 'PATH_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  AMBIGUOUS: 'AMBIGUOUS',
  DRIVE_ERROR: 'DRIVE_ERROR'
};

var ACTION_STATUSES = {
  EXECUTED: 'EXECUTED',
  SKIPPED_ALREADY_AT_TARGET: 'SKIPPED_ALREADY_AT_TARGET',
  SOURCE_MISSING: 'SOURCE_MISSING',
  TARGET_CONFLICT: 'TARGET_CONFLICT',
  EXECUTED_SOURCE_RETAINED: 'EXECUTED_SOURCE_RETAINED',
  FAILED: 'FAILED'
};

var ACTION_OPERATIONS = {
  MOVE: 'MOVE'
};

var ACTION_SYSTEM_JUNK_NAMES = {
  'desktop.ini': true,
  'thumbs.db': true,
  '.ds_store': true
};

var VERRACT_STATE_KEYS = {
  ACTIVE_PHASE: 'VERRACT_ACTIVE_PHASE',
  CURRENT_ROW: 'VERRACT_CURRENT_ROW',
  RANGE_INDEX: 'VERRACT_RANGE_INDEX',
  END_ROW: 'VERRACT_END_ROW',
  CONFIG: 'VERRACT_CONFIG',
  RUN_ID: 'VERRACT_RUN_ID',
  STARTED_AT: 'VERRACT_STARTED_AT',
  LAST_STATUS: 'VERRACT_LAST_STATUS'
};

var VERRACT_DISABLED_EXECUTION_MESSAGE =
  'Execution is not a separate phase. Use ACTION for the real folder mutation.';
